input: "/projects/wp3/Validering/pipelines/pipeline_md5sums/marple_md5sums.tsv"

reference_genome: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta"

design_bed: "/projects/wp3/nobackup/TwistCancer/Bedfiles/Twist_Cancer_230608_hg38_TE-98982205-wPGRS.merged.bed"

happy_vcf_suffix: "hard-filtered.vcf.gz"
