input: "/projects/wp3/Validering/pipelines/pipeline_md5sums/pipeline_md5sums/hastings_md5sums.tsv"

design_bed: "/data/ref_data/wp3/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed"
reference_genome: "/data/ref_data/wp3/hastings/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked_chr.fasta"

happy_vcf_suffix: "hard-filtered.vcf.gz"