input: "pipeline_md5sums/nallo_hifi_wgs_md5sums.tsv"

reference_genome: "/beegfs-storage/data/ref_genomes/GRCh38/GRCh38-GIABv3/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta"
happy_vcf_suffix: "_snvs_annotated_research.vcf.gz"
happy_vcf_suffix: "_svs_annotated_research.vcf.gz"

truvari_benchmarking:
  refdist: 2000
  chunksize: 5000
