
vcf_validation:
  mem_mb: 8000
  runtime: 240
  cpus_per_task: 1

# BAM/CRAM file processing
bam_validation:
  mem_mb: 6000
  runtime: 240
  cpus_per_task: 1

# Metrics file processing 
metrics_validation:
  mem_mb: 6000
  runtime: 240
  cpus_per_task: 1

# Miscellaneous file processing
misc_validation:
  mem_mb: 6000
  runtime: 240
  cpus_per_task: 1

# Summary and collection tasks 
summary_tasks:
  mem_mb: 6000
  runtime: 240
  cpus_per_task: 1

# Happy benchmarking tasks
happy_benchmarking:
  mem_mb: 20000
  runtime: 720
  cpus_per_task: 16

# Truvari benchmarking tasks
truvari_benchmarking:
  mem_mb: 96000
  runtime: 240
  cpus_per_task: 16

